from ..factory import Type


class chat(Type):
	id = None  # type: "int53"
	type = None  # type: "ChatType"
	title = None  # type: "string"
	photo = None  # type: "chatPhoto"
	last_message = None  # type: "message"
	order = None  # type: "int64"
	is_pinned = None  # type: "Bool"
	is_marked_as_unread = None  # type: "Bool"
	is_sponsored = None  # type: "Bool"
	can_be_deleted_only_for_self = None  # type: "Bool"
	can_be_deleted_for_all_users = None  # type: "Bool"
	can_be_reported = None  # type: "Bool"
	default_disable_notification = None  # type: "Bool"
	unread_count = None  # type: "int32"
	last_read_inbox_message_id = None  # type: "int53"
	last_read_outbox_message_id = None  # type: "int53"
	unread_mention_count = None  # type: "int32"
	notification_settings = None  # type: "chatNotificationSettings"
	pinned_message_id = None  # type: "int53"
	reply_markup_message_id = None  # type: "int53"
	draft_message = None  # type: "draftMessage"
	client_data = None  # type: "string"
