from ..factory import Type


class message(Type):
	id = None  # type: "int53"
	sender_user_id = None  # type: "int32"
	chat_id = None  # type: "int53"
	sending_state = None  # type: "MessageSendingState"
	is_outgoing = None  # type: "Bool"
	can_be_edited = None  # type: "Bool"
	can_be_forwarded = None  # type: "Bool"
	can_be_deleted_only_for_self = None  # type: "Bool"
	can_be_deleted_for_all_users = None  # type: "Bool"
	is_channel_post = None  # type: "Bool"
	contains_unread_mention = None  # type: "Bool"
	date = None  # type: "int32"
	edit_date = None  # type: "int32"
	forward_info = None  # type: "messageForwardInfo"
	reply_to_message_id = None  # type: "int53"
	ttl = None  # type: "int32"
	ttl_expires_in = None  # type: "double"
	via_bot_user_id = None  # type: "int32"
	author_signature = None  # type: "string"
	views = None  # type: "int32"
	media_album_id = None  # type: "int64"
	content = None  # type: "MessageContent"
	reply_markup = None  # type: "ReplyMarkup"
