from ..factory import Type


class webPage(Type):
	url = None  # type: "string"
	display_url = None  # type: "string"
	type = None  # type: "string"
	site_name = None  # type: "string"
	title = None  # type: "string"
	description = None  # type: "string"
	photo = None  # type: "photo"
	embed_url = None  # type: "string"
	embed_type = None  # type: "string"
	embed_width = None  # type: "int32"
	embed_height = None  # type: "int32"
	duration = None  # type: "int32"
	author = None  # type: "string"
	animation = None  # type: "animation"
	audio = None  # type: "audio"
	document = None  # type: "document"
	sticker = None  # type: "sticker"
	video = None  # type: "video"
	video_note = None  # type: "videoNote"
	voice_note = None  # type: "voiceNote"
	instant_view_version = None  # type: "int32"
