from ..factory import Type


class inputFileId(Type):
    #  file defined by its unique ID @id Unique file

    id = None  # type: "int32"


class inputFileRemote(Type):
    #  file defined by its remote ID @id Remote file

    id = None  # type: "string"


class inputFileLocal(Type):
    #  file defined by a local path @path Local path to the file

    path = None  # type: "string"


class inputFileGenerated(Type):
    #  file generated by the client @original_path Local path to
    #  file from which the file is generated; may be
    #  if there is no such file @conversion String specifying
    #  conversion applied to the original file; should be persistent
    #  application restarts @expected_size Expected size of the generated file; 0 if unknown

    original_path = None  # type: "string"
    conversion = None  # type: "string"
    expected_size = None  # type: "int32"
